import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,tick,action,ready,reward,load,save,KEY,validate} from '../static/js/game-state.js';
const memory=()=>{const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)};};
test('six plots, four crops, watering begins growth; harvest once',()=>{const s=fresh(1000);assert.equal(s.plots.length,6);assert.equal(Object.keys(s.seeds).length,4);assert(action(s,'plant',0,'radish'));tick(s,121000);assert(!ready(s,0));assert(action(s,'water',0));tick(s,181000);assert(ready(s,0));assert(action(s,'harvest',0));assert.equal(s.inventory.radish,1);assert.equal(s.seeds.radish,5);assert(!action(s,'harvest',0));assert.equal(s.inventory.radish,1);});
test('reload preserves crop and reward idempotency',()=>{const storage=memory(),s=fresh(1000);action(s,'plant',2,'tomato');action(s,'water',2);reward(s,'2026-10-04');save(storage,s);const restored=load(storage,151000).state;assert(ready(restored,2));assert(!reward(restored,'2026-10-04'));assert.equal(restored.seeds.radish,6);});
test('offline capped and backward clock does not create progress',()=>{const s=fresh(1000);tick(s,500);assert.equal(s.logicalTime,0);assert.equal(s.lastSeen,1000);tick(s,1000+3*86400000);assert.equal(s.logicalTime,86400000);assert.match(s.notice,/24/);tick(s,1000+3*86400000);assert.equal(s.logicalTime,86400000);});
test('invalid JSON gets a fresh garden and damage backup',()=>{const storage=memory();storage.setItem(KEY,'broken');const result=load(storage,1000);assert.equal(result.state.seeds.radish,4);assert.equal(storage.getItem(KEY+'-damaged'),'broken');});
test('reject negative counts, future planting, invalid crop and duplicate rewards',()=>{for(const corrupt of [s=>s.seeds.radish=-1,s=>s.plots[0]={crop:'invalid',planted:0,watered:false},s=>s.plots[0]={crop:'radish',planted:100,watered:false},s=>s.rewards=['2026-10-04','2026-10-04']]){const s=fresh(1000);corrupt(s);assert.throws(()=>validate(s));}});
test('storage unavailable uses memory; write failure is visible to UI',()=>{const fail={getItem(){throw Error();},setItem(){throw Error();}};assert.equal(load(fail).persistent,false);assert.equal(save(fail,fresh()),false);});
test('no seed and out-of-range clicks cannot write state',()=>{const s=fresh();s.seeds.radish=0;assert(!action(s,'plant',0,'radish'));assert(!action(s,'plant',6,'tomato'));assert(!action(s,'plant',-1,'tomato'));});
test('reward cannot move backwards',()=>{const s=fresh();assert(reward(s,'2026-10-04'));assert(!reward(s,'2026-10-03'));});

test('forward jump followed by corrected clock recovers without free progress',()=>{const s=fresh(1000);tick(s,1000+365*86400000);const capped=s.logicalTime;tick(s,2000);tick(s,2000);tick(s,2000);assert.equal(s.logicalTime,capped);assert.equal(s.lastSeen,2000);tick(s,3000);assert.equal(s.logicalTime,capped+1000);});

test('damaged notices and impossible reward dates are rejected',()=>{const s=fresh();s.notice=7;assert.throws(()=>validate(s));s.notice='';s.rewards=['2026-02-30'];assert.throws(()=>validate(s));assert(!reward(fresh(),'2026-02-30'));});
