import {chromium} from 'playwright-core';import assert from 'node:assert/strict';import {mkdir,readFile,writeFile,stat} from 'node:fs/promises';import {createServer} from 'node:http';import path from 'node:path';
const output=path.resolve('docs/screenshots');await mkdir(output,{recursive:true});let server;
let base=process.env.FARM_TEST_URL;
if(!base){const root=path.resolve('public');server=createServer(async(req,res)=>{try{const rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname);let file=path.resolve(root,'.'+rel);if(!file.startsWith(root+path.sep)&&file!==root)throw Error();if((await stat(file)).isDirectory())file=path.join(file,'index.html');const ext=path.extname(file);res.setHeader('content-type',({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'})[ext]||'text/plain');res.end(await readFile(file));}catch{res.statusCode=404;res.end('Not found');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;}
const browser=await chromium.launch({headless:true});const errors=[],checks=[];
try{for(const [label,width,height,mobile]of [['desktop',1280,960,false],['mobile',390,844,true]]){const context=await browser.newContext({viewport:{width,height},isMobile:mobile,hasTouch:mobile,locale:'zh-CN',timezoneId:'Asia/Shanghai',colorScheme:'light'});const page=await context.newPage();page.on('pageerror',e=>errors.push(label+' '+e.message));await page.goto(base,{waitUntil:'networkidle'});await page.locator('#plots button').first().waitFor();assert.equal(await page.locator('#plots button').count(),6);assert.equal(await page.locator('#seed-picker button').count(),4);assert(await page.locator('main').innerText());
 const sizes=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,images:[...document.querySelectorAll('img:not([hidden])')].every(i=>i.complete&&i.naturalWidth>0),font:getComputedStyle(document.querySelector('body')).fontSize}));assert(sizes.scroll<=sizes.width,'页面水平溢出');assert(sizes.images,'图片空白');
 await page.screenshot({path:path.join(output,label+'-light.png'),fullPage:true});await page.locator('#plots button').first().click();await page.waitForFunction(()=>document.querySelector('#plots button').getAttribute('aria-label').includes('浇水'));assert.match(await page.locator('#plots button').first().getAttribute('aria-label'),/浇水/);await page.locator('#plots button').first().click();await page.waitForFunction(()=>document.querySelector('#plots button').getAttribute('aria-label').includes('生长'));await page.reload({waitUntil:'networkidle'});assert.match(await page.locator('#plots button').first().getAttribute('aria-label'),/生长/);
 await page.locator('.knowledge [data-answer]').nth((await page.locator('.knowledge').getAttribute('data-correct'))==='true'?0:1).click();await page.evaluate(()=>navigator.locks?.request('qiuqiu-farm',()=>{}));const after=await page.evaluate(()=>JSON.parse(localStorage.getItem('qiuqiu-farm-v1')));await page.locator('.knowledge [data-answer]').nth((await page.locator('.knowledge').getAttribute('data-correct'))==='true'?0:1).click();await page.evaluate(()=>navigator.locks?.request('qiuqiu-farm',()=>{}));const again=await page.evaluate(()=>JSON.parse(localStorage.getItem('qiuqiu-farm-v1')));assert.equal(after.seeds.radish,again.seeds.radish,'奖励重复');
 await page.clock.install();await page.clock.fastForward(61000);await page.getByRole('button',{name:/1号地.*收获/}).click();await page.evaluate(()=>navigator.locks?.request('qiuqiu-farm',()=>{}));const harvested=await page.evaluate(()=>JSON.parse(localStorage.getItem('qiuqiu-farm-v1')));assert.equal(harvested.inventory.radish,1);await page.reload({waitUntil:'networkidle'});assert.equal((await page.evaluate(()=>JSON.parse(localStorage.getItem('qiuqiu-farm-v1')))).inventory.radish,1);
 await page.locator('#theme-toggle').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.screenshot({path:path.join(output,label+'-dark.png'),fullPage:true});
 const report=page.locator('a.read-button');assert.equal(await report.count(),1,'没有真实日报入口');await report.click();assert.match(await page.locator('.prose').innerText(),/今天的实操/);assert((await page.locator('.prose').innerText()).length>600);assert((await page.evaluate(()=>document.documentElement.scrollWidth))<=width,'正文溢出');await page.screenshot({path:path.join(output,label+'-article-dark.png'),fullPage:true});
 await page.goto(base+'/search/',{waitUntil:'networkidle'});await page.locator('#search-input').fill('排水');await page.locator('.search-result').first().waitFor();assert((await page.locator('#search-results').innerText()).includes('秋秋农场日报'));await page.locator('#search-input').fill('不存在的超级长查询词'.repeat(15));assert.equal(await page.locator('.search-result').count(),0);assert((await page.evaluate(()=>document.documentElement.scrollWidth))<=width);
 await page.goto(base);await page.evaluate(()=>localStorage.setItem('qiuqiu-farm-v1','damaged'));await page.reload({waitUntil:'networkidle'});assert.match(await page.locator('#game-status').innerText(),/损坏/);await context.close();checks.push({label,...sizes,checks:'seed/water/persistence/harvest/reward/themes/article/search/damage passed'});}
 const context=await browser.newContext();await context.addInitScript(()=>{Storage.prototype.getItem=function(){throw Error('unavailable');};Storage.prototype.setItem=function(){throw Error('unavailable');};});const p=await context.newPage();await p.goto(base,{waitUntil:'networkidle'});assert.match(await p.locator('#game-status').innerText(),/存储不可用/);await p.locator('#plots button').first().click();await p.waitForFunction(()=>document.querySelector('#plots button').getAttribute('aria-label').includes('浇水'));assert.match(await p.locator('#plots button').first().getAttribute('aria-label'),/浇水/);await context.close();assert.deepEqual(errors,[]);const receipt={url:base,testedAt:new Date().toISOString(),browser:browser.version(),checks,storageUnavailable:'passed',pageErrors:errors};await writeFile('docs/BROWSER_RECEIPT.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));
}finally{await browser.close();if(server)await new Promise(r=>server.close(r));}
